name: kb-sdk test

on:
  [push, pull_request]

jobs:

  install_kbsdk_and_test_appdev:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: pull and run docker image
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN_APPDEV }}
      run: |
        docker pull ialarmedalien/kb-sdk
        docker run ialarmedalien/kb-sdk genscript > $GITHUB_WORKSPACE/kb-sdk
        chmod 755 $GITHUB_WORKSPACE/kb-sdk
        $GITHUB_WORKSPACE/kb-sdk test

  install_kbsdk_and_test_ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: pull and run docker image
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN_CI }}
      run: |
        mkdir -p test_local
        cp ci.test.cfg test_local/test.cfg
        docker pull ialarmedalien/kb-sdk
        docker run ialarmedalien/kb-sdk genscript > $GITHUB_WORKSPACE/kb-sdk
        chmod 755 $GITHUB_WORKSPACE/kb-sdk
        $GITHUB_WORKSPACE/kb-sdk test
